"""First migration

Revision ID: 7e582aff64c7
Revises:
Create Date: 2024-04-01 08:45:41.580817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e582aff64c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'circuit',
        sa.Column('circuit_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('circuit_id')
    )
    op.create_table(
        'team',
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table(
        'driver',
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('nationality', sa.String(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        # sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
        sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table(
        'fastest_lap',
        sa.Column('fastest_lap_id', sa.Integer(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=True),
        sa.Column('race_id', sa.Integer(), nullable=True),
        sa.Column('time', sa.String(), nullable=True),
        # sa.ForeignKeyConstraint(
        #     ['driver_id'], ['driver.driver_id'], ),
        # sa.ForeignKeyConstraint(['race_id'], ['race.race_id'], ),
        sa.PrimaryKeyConstraint('fastest_lap_id')
    )
    op.create_table(
        'race',
        sa.Column('race_id', sa.Integer(), nullable=False),
        sa.Column('circuit_id', sa.Integer(), nullable=True),
        sa.Column('fastest_lap_id', sa.Integer(), nullable=True),
        sa.Column('winner', sa.String(), nullable=True),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('date', sa.String(), nullable=True),
        # sa.ForeignKeyConstraint(
        #     ['circuit_id'], ['circuit.circuit_id'], ),
        # sa.ForeignKeyConstraint(['fastest_lap_id'], [
        #     'fastest_lap.fastest_lap_id'], ),
        sa.PrimaryKeyConstraint('race_id')
    )
    op.create_table(
        'race_result',
        sa.Column('result_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('driver_id', sa.Integer(), nullable=True),
        sa.Column('race_id', sa.Integer(), nullable=True),
        sa.Column('fastest_lap_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['driver_id'], ['driver.driver_id'], ),
        sa.ForeignKeyConstraint(['fastest_lap_id'], [
            'fastest_lap.fastest_lap_id'], ),
        sa.ForeignKeyConstraint(['race_id'], ['race.race_id'], ),
        sa.PrimaryKeyConstraint('result_id')
    )
    # Add foreign key constraints
    op.create_foreign_key(
        'fk_race_circuit_id', 'race', 'circuit', ['circuit_id'], ['circuit_id']
    )

    op.create_foreign_key(
        'fk_fastest_lap_driver_id', 'fastest_lap', 'driver', [
            'driver_id'], ['driver_id']
    )

    op.create_foreign_key(
        'fk_fastest_lap_race_id', 'fastest_lap', 'race', [
            'race_id'], ['race_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_result')
    op.drop_table('driver')
    op.drop_table('team')
    op.drop_table('race')
    op.drop_table('fastest_lap')
    op.drop_table('circuit')
    # ### end Alembic commands ###
