name: build and Deploy image

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Add profile credentials to ~/.aws/credentials
              run: |
                mkdir -p ~/.aws
                echo "[terraform]" > ~/.aws/credentials
                echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
                echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials

            - name: Set up terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform init
              run: terraform -chdir=terraform init

            - name: Terraform plan
              env:
                TF_VAR_host_name: ${{secrets.DB_HOST}}
                TF_VAR_db_user: ${{secrets.DB_NAME}}
                TF_VAR_db_password: ${{secrets.DB_PASSWORD}}
                TF_VAR_db_port: ${{secrets.DB_PORT}}
                TF_VAR_db_name: ${{secrets.DB_USER}}
              run: terraform -chdir=terraform plan
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        # if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Add profile credentials to ~/.aws/credentials
              run: |
                mkdir -p ~/.aws
                echo "[terraform]" > ~/.aws/credentials
                echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
                echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials

                echo "[profile terraform]" > ~/.aws/config
                echo "region=us-east-1" >> ~/.aws/config
                cat ~/.aws/credentials
                cat ~/.aws/config
            
            
            - name: Set up terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform init
              run: terraform -chdir=terraform init

            - name: Terraform apply
              env:
                TF_VAR_host_name: ${{secrets.DB_HOST}}
                TF_VAR_db_user: ${{secrets.DB_NAME}}
                TF_VAR_db_password: ${{secrets.DB_PASSWORD}}
                TF_VAR_db_port: ${{secrets.DB_PORT}}
                TF_VAR_db_name: ${{secrets.DB_USER}}
              run: terraform -chdir=terraform apply -auto-approve
