name: API Tests

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./spacex_data/

        strategy:
            matrix:
                python-version: [3.12]

        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Change working dir
              run: cd ../../app

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Test App Code
              run: pytest
        