name: API Tests

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .

        strategy:
            matrix:
                python-version: [3.12]

        env:
            MODE: "dev"
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_NAME: ${{ secrets.DB_NAME }}

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Test App Code
              run: pytest
        